In [135]:
from pyforest import *

In [136]:
df1 = pd.read_csv('Plant_1_Generation_Data.csv')
df2 = pd.read_csv('Plant_1_Weather_Sensor_Data.csv')

In [137]:
df1.head()

          DATE_TIME  PLANT_ID  ... DAILY_YIELD  TOTAL_YIELD
0  15-05-2020 00:00   4135001  ...         0.0    6259559.0
1  15-05-2020 00:00   4135001  ...         0.0    6183645.0
2  15-05-2020 00:00   4135001  ...         0.0    6987759.0
3  15-05-2020 00:00   4135001  ...         0.0    7602960.0
4  15-05-2020 00:00   4135001  ...         0.0    7158964.0

[5 rows x 7 columns]

In [138]:
df2.head()

             DATE_TIME  PLANT_ID  ... MODULE_TEMPERATURE  IRRADIATION
0  2020-05-15 00:00:00   4135001  ...          22.857507          0.0
1  2020-05-15 00:15:00   4135001  ...          22.761668          0.0
2  2020-05-15 00:30:00   4135001  ...          22.592306          0.0
3  2020-05-15 00:45:00   4135001  ...          22.360852          0.0
4  2020-05-15 01:00:00   4135001  ...          22.165423          0.0

[5 rows x 6 columns]

In [139]:
df1 = df1.drop(['PLANT_ID', 'SOURCE_KEY'], axis =1 )
df2 = df2.drop(['PLANT_ID', 'SOURCE_KEY'], axis = 1)

In [140]:
df1['DATE_TIME'] = pd.to_datetime(df1['DATE_TIME'])
df2['DATE_TIME'] = pd.to_datetime(df2['DATE_TIME'])

C:\Users\USER\AppData\Local\Temp\ipykernel_11056\4140187588.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df1['DATE_TIME'] = pd.to_datetime(df1['DATE_TIME'])

In [141]:
df1['HOUR'] = df1['DATE_TIME'].dt.hour
df1['DAY'] = df1['DATE_TIME'].dt.dayofyear
df1['MONTH'] = df1['DATE_TIME'].dt.month

df1.head()

   DATE_TIME  DC_POWER  AC_POWER  DAILY_YIELD  TOTAL_YIELD  HOUR  DAY  MONTH
0 2020-05-15       0.0       0.0          0.0    6259559.0     0  136      5
1 2020-05-15       0.0       0.0          0.0    6183645.0     0  136      5
2 2020-05-15       0.0       0.0          0.0    6987759.0     0  136      5
3 2020-05-15       0.0       0.0          0.0    7602960.0     0  136      5
4 2020-05-15       0.0       0.0          0.0    7158964.0     0  136      5

In [142]:

df1 = df1.set_index('DATE_TIME')
df1_i5mins = df1.resample('15T').mean()

df1_15mins = df1_i5mins.reset_index()

C:\Users\USER\AppData\Local\Temp\ipykernel_11056\457482350.py:2: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df1_i5mins = df1.resample('15T').mean()

In [143]:
final_df = pd.merge(df1_15mins, df2, on = 'DATE_TIME')
final_df

               DATE_TIME  DC_POWER  ...  MODULE_TEMPERATURE  IRRADIATION
0    2020-05-15 00:00:00       0.0  ...           22.857507          0.0
1    2020-05-15 00:15:00       0.0  ...           22.761668          0.0
2    2020-05-15 00:30:00       0.0  ...           22.592306          0.0
3    2020-05-15 00:45:00       0.0  ...           22.360852          0.0
4    2020-05-15 01:00:00       0.0  ...           22.165423          0.0
...                  ...       ...  ...                 ...          ...
3177 2020-06-17 22:45:00       0.0  ...           21.480377          0.0
3178 2020-06-17 23:00:00       0.0  ...           21.389024          0.0
3179 2020-06-17 23:15:00       0.0  ...           20.709211          0.0
3180 2020-06-17 23:30:00       0.0  ...           20.734963          0.0
3181 2020-06-17 23:45:00       0.0  ...           20.427972          0.0

[3182 rows x 11 columns]

In [144]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3182 entries, 0 to 3181
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            3182 non-null   datetime64[ns]
 1   DC_POWER             3157 non-null   float64
 2   AC_POWER             3157 non-null   float64
 3   DAILY_YIELD          3157 non-null   float64
 4   TOTAL_YIELD          3157 non-null   float64
 5   HOUR                 3157 non-null   float64
 6   DAY                  3157 non-null   float64
 7   MONTH                3157 non-null   float64
 8   AMBIENT_TEMPERATURE  3182 non-null   float64
 9   MODULE_TEMPERATURE   3182 non-null   float64
 10  IRRADIATION          3182 non-null   float64
dtypes: datetime64[ns](1), float64(10)
memory usage: 273.6 KB

In [145]:
df = final_df.drop(['DAILY_YIELD', 'TOTAL_YIELD','MONTH', 'DAY', 'DATE_TIME'], axis = 1)
df.head()

   DC_POWER  AC_POWER  ...  MODULE_TEMPERATURE  IRRADIATION
0       0.0       0.0  ...           22.857507          0.0
1       0.0       0.0  ...           22.761668          0.0
2       0.0       0.0  ...           22.592306          0.0
3       0.0       0.0  ...           22.360852          0.0
4       0.0       0.0  ...           22.165423          0.0

[5 rows x 6 columns]

In [146]:
df.HOUR.value_counts()

HOUR
10.0    136
8.0     136
18.0    136
20.0    136
9.0     136
19.0    136
11.0    135
21.0    135
22.0    134
13.0    134
17.0    134
12.0    134
7.0     133
15.0    132
16.0    132
14.0    131
4.0     128
3.0     128
2.0     128
6.0     126
23.0    125
1.0     124
5.0     124
0.0     124
Name: count, dtype: int64

In [147]:
df.to_csv('final_solar_dataset.csv', index = False)